### ISSUE TITLE
14 - Connect API to UI

### ISSUE THREAD

**Issue by kelseydonavin** [kelseydonavin/MC_UI#16]
Pre-requirements:
Issue 4 is complete, API repo is set up in GitHub and accessible 

Requirements:
- UI is can receive data from the API
- UI can send data to the API
- API can send data to the UI

**Comment by kelseydonavin** [comment]
This issue requires documentation of process.

**Comment by lshearer20** [comment]
Created the new C# API via the Tutorial posted by Kelsey in LINKs on Discord. Followed up until PART 4, which I believe is where this connecting the API to UI part begins.

**Comment by kelseydonavin** [comment]
Closed, please refer to update issue

**Comment by kelseydonavin** [comment]
Implementing as backup to GraphQL

**Comment by ajaeminkim93** [comment]
Main Point: I got the UI accessing the endpoint API/Values from the API and retrieving data. It is being displayed to the console at the moment.

Extra: The data is being extracted properly. This is a test just to make sure we can communicate between the frontend and the backend. If we are not implementing graphQL, we need to create more endpoints for the functions we will be using. The data needs to be stored possibly using the angular store function so that it can update the UI in real time.

**Comment by kelseydonavin** [comment]
Not closing issues until dev meeting

**Comment by kkjw94** [comment]
Completed connecting UI and API 
Using graphQL will be easier, faster, and way less codes; no need to make all the endpoints per each.
